
module.exports = {

	"DEFAULT": "Action Performed Successfully.",
	"DEFAULTERR": "Oops! Something went wrong!!",
	"DEFAULT_AUTH": "You are not authenticated to perform this action.",
	"DEFAULTAUTHERR": "You are not authenticated to perform this action.",
	"DEFAULT_INTERNAL_SERVER_ERROR": "Internal server error",
	"REQUIRED_FIELD_VALIDATION": "Please fill in the mandatory fields.",
	"NOT_FOUND": "Not found",
	"UNAUTHORIZED": "User not Authorized",

	"EMAIL_ALREADY_EXISTS": "An account with this Email id already exists.",
	"EMAIL_NOT_VERIFIED": "Your email is not verified",
	"INVALIDE_ACTIVATION_CODE": "Your email verification link has expired.",
	"INVALIDE_EMAIL_PASSWORD": "You have added an incorrect details. Please check.",
	"EMAIL_NOT_FOUND": "Entered EmailId doesn't exist.",
	"INVALIDE_RESET_PASSWORD_CODE": "Your Reset password link is not proper. Please try again.",
	"USER_NOT_FOUND": "This user doesn't exist. Please try again.",
	"SESSION_NOT_FOUND": "This session doesn't exist.",
	"REVIEW_NOT_FOUND": "this review doesn't exist",
	"CHANGE_PASSWORD_SUCCESULLY": "Your password has been changed.",
	"USER_VERIFIED_SUCCESULLY": "You account has been verified.",
	"USER_ACTIVATE_SUCCESULLY": "You account has been activated.",
	"USER_UPDATE_SUCCESULLY": "Your account has been updated.",
	"RESET_PASSWORD_SUCCESULLY": "Your Password has been changed.",
	"RESET_PASSWORD_MAIL_SEND_SUCCESSFULLY": "We have sent a reset password link on your registered email address.",
	"INVALIDE_OLD_PASSWORD": "The entered old password doesn't match.",
	"NOT_ACTIVE_USER": "This user account is not active.Please contact admin for the same",
	"INVALIDE_STUDENT_CODE": "You have entered a wrong student code. Please try again.",
	"NOT_ACTIVE_STUDENT": "The entered student code is not active anymore.",
	"ADMIN_NOT_ALLOW_DE_ACTIVE_YOUR_SELF": "Since you are an Admin you cannot deactivate your own account.",
	"TOKEN_NOT_FOUND": "Token Not Found",
	"TOKEN_EXPIRED": "Your current token has expired",
	"INVALID_TOKEN": "Your token is invalid or expired",

	"PLAN_NOT_SELECTED": "You have not selected your subscription plan.",
	"NOT_ALLOWED_IN_FREE_PLAN": "Not Allow In Free Plan",
	"LIMITED_CLASSROOM_ALLOWED_ON_SELECTED_PLAN": "You have subscribed to a free plan. To create more classrooms you can upgrade your account to a paid version. ",
	"LIMITED_STUDENT_ALLOWED_ON_SELECTED_PLAN": "You have subscribed to a free plan. To create more classrooms you can upgrade your account to a paid version.",
	"PURCHASE_SUBSCRIPTION_SUCCESULLY": "You have subscribed to a paid version of Story Duel.",
	"UPDATE_SUBSCRIPTION_SUCCESULLY": "Your subscription has been updated.",
	"UPGRADE_SUBSCRIPTION_SUCCESULLY": "Your subscription has been upgraded.",
	"UNSUBSCRIBE_SUBSCRIPTION": "Your subscription has been downgraded.",
	"UPGRADE_SUBSCRIPTION": "Your subscription has been upgraded successfully.",
	"UNSUBSCRIBE_SUBSCRIPTION_SUCCESULLY": "Your subscription has been downgraded.",
	"LOGIN_SUCCESSFULLY": "Login Successfully",
	"REQUEST_NOT_ALLOWED": "You don't have enough permissions for this action.",
	"USER_DEACTIVATE_SUCCESULLY": "Your account has been deactivated.",
	"ONLY_ADMIN_CAN_ACTIVE_USER": "You have to contact Admin to activate a user.",

	"RESET_PASSWORD": "Reset Password",
	"EMAIL_VERIFICATION": "Email Verification",
	"ACCOUNT_DEACTIVATE": "Story Duel account deactivated",
	"DE_ACTIVE_USER": "De Active User",
	"UPDATE_SUBSCRIPTION": "Story Duel subscription updated",
	"PURCHASE_SUBSCRIPTION": "Story Duel subscription",
	"WELCOME_USER": "Welcome to Story Duel",
	"ACCOUNT_ACTIVATE": "Activation for Story Duel",
	"CHANGE_PASSWORD": "New Story Duel Password",


	"CREATE_STUDENT": "Create student",
	"STUDENT_NOT_FOUND": "You have not added any students to your classroom. Add your students here.",
	"STUDENT_UPDATE_SUCCESULLY": "Your student details are updated.",
	"TUTOR_UPDATE_SUCCESULLY": "Your tutor details are updated.",
	"TUTOR_VERIFIED_SUCCESULLY": "Your tutor details are verified.",
	"STUDENT_DELETE_SUCCESULLY": "Student has been removed.",
	"STUDENT_NOT_BELONG_TO_USER": "You don't have permissions for this student.",
	"STUDENT_BULK_UPLOAD": "Your student list have been successfully uploaded.",
	"FILE_NOT_FOUND": "File Not Found",
	"FILE_Allow_ONLY_CSV": "You can only import students with a CSV File.",
	"FILE_IS_EMPTY": "File Is Empty",
	"FILE_DATA_IS_NOT_VALID": "File Data Is Not Valid",
	"STUDENT_BADGES_CREATE_SUCCESULLY": "Student badges create successfully",
	"STUDENT_ACTIVATE_SUCCESULLY": "This student has been activated.",
	"STUDENT_DEACTIVATE_SUCCESULLY": "This student has been deactivated.",

	"USER_SIGNUP": "User Registered Successfully",

	"SESSION_CREATED_SUCCESULLY": "Session has been created Successfully.",
	"SESSION_UPDATED_SUCCESULLY": "Session has been updated Successfully.",
	"REVIEW_ADDED_SUCCESULLY": "Review added Successfully.",
	"REVIEW_UPDATED_SUCCESULLY": "Review updated Successfully.",


}
